name: Docker Images Builder

# when a PR is closed on main, run the workflow
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    # additionaly the PR must be merged, in order to execute the steps
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}-backend:latest
      -
        name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}-frontend:latest
